### ISSUE TITLE
`head`

### ISSUE THREAD

**Issue by ghost** [gaokohl/Dasmoto-project#1]
https://github.com/gaokohl/Dasmoto-project/blob/master/index.html#L6-L7

Nice job providing your web page a relevant `title` and providing a _relative_ file path to your stylesheet instead of an absolute one. 👍 

Go ahead and write the whole link tag in a single line though, just to make sure you (or someone using your code) doesn't end up breaking your styles.

**Comment by gaokohl** [comment]
Thanks for the review and the suggestions!
